##
#Clone and pull the repo
##
- name: Set up git configuration
  dnf: name=git state=latest
  become: yes

- name: Clone of pull the latest code
  git: repo={{ code_repository_url }}
        dest={{ app_dir }}